name: Deploy to Surge

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # - name: Install Dependencies
    #   run: npm install

    - name: Install Surge
      run: npm install -g surge

    - name: Deploy to Surge
      env:
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      run: surge ./ https://aaryan-dadu-l1.surge.sh --token $SURGE_TOKEN
